name: check_code_quality

on:
# Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install env manager
        run: python -m pip install --upgrade pip~=21.2.4 poetry~=1.1.11 setuptools~=59.0.1

      - name: Install dependencies
        run: poetry install

      - name: Run pre-commit linters
        run: poetry run pre-commit run -a

  test:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform:
          - ubuntu-latest
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "pypy3"
        include:
          - platform: ubuntu-latest
            python-version: pypy3

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: python -m pip install --upgrade pip~=21.2.4 poetry~=1.1.11 setuptools~=59.0.1 tox~=3.24.1  tox-gh-actions~=2.6.0 tox-poetry-installer~=0.8.2

    - name: Test with tox
      run: tox
